-- =============================================================================
-- Rideva — ONE-SHOT SETUP (run in Supabase Dashboard → SQL Editor)
-- =============================================================================
-- ⚠️  DESTRUCTIVE: drops the existing public schema, then builds Rideva clean.
-- Generated by concatenating migrations 0000 → 0003. Does NOT include seed data.
-- To add demo accounts afterwards, run supabase/seed.sql separately.
-- =============================================================================


-- >>>>>>>>>>>>>>>>>>>> migrations/0000_reset.sql >>>>>>>>>>>>>>>>>>>>

-- =============================================================================
-- Rideva — Clean-slate reset  (⚠️ DESTRUCTIVE)
-- =============================================================================
-- The target project already contains unrelated tables from a previous app.
-- This migration runs FIRST and wipes the entire `public` schema so the Rideva
-- schema (0001→0003) applies onto a clean database.
--
-- It only touches `public` and one app-owned trigger on `auth.users`. The
-- Supabase-managed `auth`, `storage`, and `realtime` schemas are left intact.
--
-- This runs exactly once per environment (migration history is tracked), so it
-- will NOT nuke data on subsequent `supabase db push` deployments.
-- =============================================================================

-- Drop our auth → profile provisioning trigger if a prior version exists
-- (the function lives in public and would be removed by the cascade below, but
--  the trigger sits on auth.users so we drop it explicitly first).
drop trigger if exists on_auth_user_created on auth.users;

-- Nuke everything in public (tables, types, functions, views from the old app).
drop schema if exists public cascade;

-- Recreate an empty public schema with the standard Supabase grants so the
-- anon / authenticated / service roles work exactly as on a fresh project.
create schema public;

grant usage on schema public to anon, authenticated, service_role;
grant all  on schema public to postgres, service_role;

alter default privileges in schema public
  grant all on tables    to postgres, anon, authenticated, service_role;
alter default privileges in schema public
  grant all on functions to postgres, anon, authenticated, service_role;
alter default privileges in schema public
  grant all on sequences to postgres, anon, authenticated, service_role;

comment on schema public is 'standard public schema (reset for Rideva)';

-- >>>>>>>>>>>>>>>>>>>> migrations/0001_initial_schema.sql >>>>>>>>>>>>>>>>>>>>

-- =============================================================================
-- Rideva — Initial Schema
-- PostgreSQL 15 (Supabase) with PostGIS for geospatial queries
-- =============================================================================
-- This migration creates the core relational model for the ride-booking
-- platform: identities, driver profiles, rides, payments, ratings, realtime
-- location streams and earnings ledger.
--
-- Design notes:
--   * `auth.users` is owned by Supabase Auth. We mirror app-level identity into
--     `public.profiles` (1:1) keyed by the auth uid.
--   * Geography columns use SRID 4326 (WGS84 lon/lat). We index them with GiST.
--   * Money is stored as integer minor units (cents) to avoid float drift.
--   * Enums are first-class Postgres types for status machines.
-- =============================================================================

create extension if not exists "postgis";
create extension if not exists "pgcrypto";       -- gen_random_uuid()
create extension if not exists "pg_trgm";         -- fuzzy search on addresses

-- -----------------------------------------------------------------------------
-- Enums
-- -----------------------------------------------------------------------------
create type user_role        as enum ('passenger', 'driver', 'admin');
create type account_status   as enum ('active', 'suspended', 'banned', 'pending');
create type driver_status    as enum ('offline', 'online', 'on_trip');
create type vehicle_class     as enum ('economy', 'comfort', 'xl', 'premium');
create type ride_status      as enum (
  'requested',     -- passenger created request, searching for driver
  'matching',      -- offers being dispatched to drivers
  'accepted',      -- a driver accepted, en route to pickup
  'arriving',      -- driver close to pickup
  'arrived',       -- driver at pickup, waiting
  'in_progress',   -- trip started
  'completed',     -- trip finished, awaiting payment settle
  'cancelled',     -- cancelled by passenger/driver/system
  'no_drivers'     -- matching exhausted
);
create type ride_offer_status as enum ('pending', 'accepted', 'rejected', 'expired', 'cancelled');
create type payment_method    as enum ('cash', 'card', 'wallet');
create type payment_status    as enum ('pending', 'authorized', 'paid', 'failed', 'refunded');
create type cancelled_by       as enum ('passenger', 'driver', 'system');
create type notification_type as enum (
  'ride_requested', 'ride_accepted', 'driver_arriving', 'driver_arrived',
  'ride_started', 'ride_completed', 'payment_confirmed', 'ride_cancelled', 'system'
);

-- -----------------------------------------------------------------------------
-- profiles  (1:1 with auth.users)
-- -----------------------------------------------------------------------------
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  role          user_role      not null default 'passenger',
  status        account_status not null default 'active',
  full_name     text           not null check (char_length(full_name) between 1 and 120),
  phone         text           unique,
  email         text           unique,
  avatar_url    text,
  rating_avg    numeric(3,2)   not null default 5.00 check (rating_avg between 0 and 5),
  rating_count  integer        not null default 0 check (rating_count >= 0),
  push_token    text,                       -- Expo push token
  created_at    timestamptz    not null default now(),
  updated_at    timestamptz    not null default now()
);
comment on table public.profiles is 'App-level identity, 1:1 with auth.users.';

create index profiles_role_idx   on public.profiles (role);
create index profiles_status_idx on public.profiles (status);
create index profiles_name_trgm  on public.profiles using gin (full_name gin_trgm_ops);

-- -----------------------------------------------------------------------------
-- drivers  (1:1 extension of a profile with role='driver')
-- -----------------------------------------------------------------------------
create table public.drivers (
  id                 uuid primary key references public.profiles(id) on delete cascade,
  status             driver_status  not null default 'offline',
  vehicle_class      vehicle_class  not null default 'economy',
  vehicle_make       text,
  vehicle_model      text,
  vehicle_color      text,
  license_plate      text           unique,
  license_number     text,
  is_verified        boolean        not null default false,
  -- denormalised live location for fast matching (also streamed in driver_locations)
  current_location   geography(Point, 4326),
  heading            numeric(5,2),          -- compass degrees 0..360
  speed_kmh          numeric(6,2),
  location_updated_at timestamptz,
  total_trips        integer        not null default 0,
  created_at         timestamptz    not null default now(),
  updated_at         timestamptz    not null default now()
);
comment on table public.drivers is 'Driver-specific data; current_location powers the matching geo-query.';

-- GiST index over the live location — the heart of nearest-driver search.
create index drivers_location_gix on public.drivers using gist (current_location);
-- Partial index: matching only ever scans online & verified drivers.
create index drivers_online_idx on public.drivers (status)
  where status = 'online' and is_verified = true;

-- -----------------------------------------------------------------------------
-- saved_locations  (passenger favourites: home, work, custom)
-- -----------------------------------------------------------------------------
create table public.saved_locations (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  label       text not null check (char_length(label) between 1 and 60),
  address     text not null,
  point       geography(Point, 4326) not null,
  created_at  timestamptz not null default now(),
  unique (user_id, label)
);
create index saved_locations_user_idx on public.saved_locations (user_id);

-- -----------------------------------------------------------------------------
-- rides  (the central trip aggregate)
-- -----------------------------------------------------------------------------
create table public.rides (
  id                 uuid primary key default gen_random_uuid(),
  passenger_id       uuid not null references public.profiles(id) on delete restrict,
  driver_id          uuid          references public.profiles(id) on delete set null,
  status             ride_status not null default 'requested',
  vehicle_class      vehicle_class not null default 'economy',

  -- locations
  pickup_address     text not null,
  pickup_point       geography(Point, 4326) not null,
  dropoff_address    text not null,
  dropoff_point      geography(Point, 4326) not null,

  -- route / estimate (filled at request time)
  distance_m         integer  check (distance_m >= 0),     -- planned distance, metres
  duration_s         integer  check (duration_s >= 0),     -- planned duration, seconds
  route_polyline     text,                                 -- encoded polyline for replay

  -- fare (minor units, e.g. cents). estimate at request, final at completion.
  currency           char(3)  not null default 'USD',
  fare_estimate      integer  check (fare_estimate >= 0),
  fare_final         integer  check (fare_final >= 0),
  surge_multiplier   numeric(4,2) not null default 1.00 check (surge_multiplier >= 1),

  payment_method     payment_method not null default 'cash',

  -- lifecycle timestamps
  requested_at       timestamptz not null default now(),
  accepted_at        timestamptz,
  arrived_at         timestamptz,
  started_at         timestamptz,
  completed_at       timestamptz,
  cancelled_at       timestamptz,
  cancelled_by       cancelled_by,
  cancellation_reason text,

  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),

  -- a passenger may only have one "live" ride at a time (enforced via partial unique below)
  constraint dropoff_differs_from_pickup
    check (st_distance(pickup_point, dropoff_point) > 10)
);
comment on table public.rides is 'Central trip aggregate; status drives the realtime state machine.';

create index rides_passenger_idx on public.rides (passenger_id, created_at desc);
create index rides_driver_idx    on public.rides (driver_id, created_at desc);
create index rides_status_idx    on public.rides (status);
create index rides_pickup_gix    on public.rides using gist (pickup_point);

-- A passenger can only have ONE active ride at any time.
create unique index rides_one_active_per_passenger
  on public.rides (passenger_id)
  where status in ('requested','matching','accepted','arriving','arrived','in_progress');

-- A driver can only be on ONE active ride at any time.
create unique index rides_one_active_per_driver
  on public.rides (driver_id)
  where status in ('accepted','arriving','arrived','in_progress') and driver_id is not null;

-- -----------------------------------------------------------------------------
-- ride_offers  (dispatch ledger: which drivers were offered which ride)
-- -----------------------------------------------------------------------------
create table public.ride_offers (
  id          uuid primary key default gen_random_uuid(),
  ride_id     uuid not null references public.rides(id) on delete cascade,
  driver_id   uuid not null references public.profiles(id) on delete cascade,
  status      ride_offer_status not null default 'pending',
  distance_m  integer,                       -- driver→pickup distance at offer time
  eta_s       integer,                       -- estimated seconds to pickup
  offered_at  timestamptz not null default now(),
  expires_at  timestamptz not null,
  responded_at timestamptz,
  unique (ride_id, driver_id)
);
create index ride_offers_ride_idx   on public.ride_offers (ride_id);
create index ride_offers_driver_idx on public.ride_offers (driver_id, status);
-- Only one pending offer per driver at a time (so we don't double-book a driver).
create unique index ride_offers_one_pending_per_driver
  on public.ride_offers (driver_id) where status = 'pending';

-- -----------------------------------------------------------------------------
-- driver_locations  (high-frequency location stream, time-series)
-- -----------------------------------------------------------------------------
create table public.driver_locations (
  id          bigint generated always as identity primary key,
  driver_id   uuid not null references public.profiles(id) on delete cascade,
  ride_id     uuid references public.rides(id) on delete set null,
  point       geography(Point, 4326) not null,
  heading     numeric(5,2),
  speed_kmh   numeric(6,2),
  recorded_at timestamptz not null default now()
);
-- Most reads are "latest point for ride X" or "track for ride X".
create index driver_locations_ride_idx on public.driver_locations (ride_id, recorded_at desc);
create index driver_locations_driver_idx on public.driver_locations (driver_id, recorded_at desc);

-- -----------------------------------------------------------------------------
-- payments
-- -----------------------------------------------------------------------------
create table public.payments (
  id              uuid primary key default gen_random_uuid(),
  ride_id         uuid not null unique references public.rides(id) on delete cascade,
  payer_id        uuid not null references public.profiles(id) on delete restrict,
  method          payment_method not null,
  status          payment_status not null default 'pending',
  currency        char(3) not null default 'USD',
  -- fare breakdown (minor units)
  base_fare       integer not null default 0 check (base_fare >= 0),
  distance_fare   integer not null default 0 check (distance_fare >= 0),
  time_fare       integer not null default 0 check (time_fare >= 0),
  surge_amount    integer not null default 0 check (surge_amount >= 0),
  booking_fee     integer not null default 0 check (booking_fee >= 0),
  tip_amount      integer not null default 0 check (tip_amount >= 0),
  total_amount    integer not null check (total_amount >= 0),
  -- Stripe-ready fields (nullable; populated when card flow is enabled)
  stripe_payment_intent_id text,
  stripe_charge_id         text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index payments_payer_idx on public.payments (payer_id, created_at desc);

-- -----------------------------------------------------------------------------
-- earnings  (driver ledger entry per completed ride)
-- -----------------------------------------------------------------------------
create table public.earnings (
  id              uuid primary key default gen_random_uuid(),
  driver_id       uuid not null references public.profiles(id) on delete cascade,
  ride_id         uuid not null unique references public.rides(id) on delete cascade,
  payment_id      uuid references public.payments(id) on delete set null,
  currency        char(3) not null default 'USD',
  gross_amount    integer not null check (gross_amount >= 0),   -- total fare
  platform_fee    integer not null default 0 check (platform_fee >= 0),
  net_amount      integer not null check (net_amount >= 0),     -- gross - fee
  created_at      timestamptz not null default now()
);
create index earnings_driver_idx on public.earnings (driver_id, created_at desc);

-- -----------------------------------------------------------------------------
-- ratings  (bidirectional: passenger↔driver, one per direction per ride)
-- -----------------------------------------------------------------------------
create table public.ratings (
  id          uuid primary key default gen_random_uuid(),
  ride_id     uuid not null references public.rides(id) on delete cascade,
  rater_id    uuid not null references public.profiles(id) on delete cascade,
  ratee_id    uuid not null references public.profiles(id) on delete cascade,
  score       smallint not null check (score between 1 and 5),
  comment     text check (char_length(comment) <= 500),
  created_at  timestamptz not null default now(),
  unique (ride_id, rater_id)        -- one rating per rater per ride
);
create index ratings_ratee_idx on public.ratings (ratee_id);

-- -----------------------------------------------------------------------------
-- ride_reports  (dispute / safety reports)
-- -----------------------------------------------------------------------------
create table public.ride_reports (
  id          uuid primary key default gen_random_uuid(),
  ride_id     uuid not null references public.rides(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  category    text not null,
  description text not null check (char_length(description) between 1 and 2000),
  resolved    boolean not null default false,
  resolved_by uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now()
);
create index ride_reports_open_idx on public.ride_reports (resolved) where resolved = false;

-- -----------------------------------------------------------------------------
-- notifications  (in-app feed; push delivery handled by edge function)
-- -----------------------------------------------------------------------------
create table public.notifications (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references public.profiles(id) on delete cascade,
  type        notification_type not null,
  title       text not null,
  body        text not null,
  data        jsonb not null default '{}'::jsonb,
  read_at     timestamptz,
  created_at  timestamptz not null default now()
);
create index notifications_user_idx on public.notifications (user_id, created_at desc);
create index notifications_unread_idx on public.notifications (user_id) where read_at is null;

-- -----------------------------------------------------------------------------
-- pricing_config  (per vehicle-class tariff; editable from admin)
-- -----------------------------------------------------------------------------
create table public.pricing_config (
  vehicle_class    vehicle_class primary key,
  currency         char(3) not null default 'USD',
  base_fare        integer not null,          -- minor units
  per_km           integer not null,          -- minor units per km
  per_min          integer not null,          -- minor units per minute
  booking_fee      integer not null default 0,
  min_fare         integer not null,
  platform_fee_bps integer not null default 2000,  -- 20.00% in basis points
  updated_at       timestamptz not null default now()
);

insert into public.pricing_config (vehicle_class, base_fare, per_km, per_min, booking_fee, min_fare) values
  ('economy', 250, 120, 25, 100, 500),
  ('comfort', 350, 160, 35, 150, 700),
  ('xl',      450, 200, 45, 200, 900),
  ('premium', 600, 280, 60, 250, 1200);

-- >>>>>>>>>>>>>>>>>>>> migrations/0002_functions_triggers.sql >>>>>>>>>>>>>>>>>>>>

-- =============================================================================
-- Rideva — Functions, Triggers & Stored Procedures
-- =============================================================================
-- Business logic that must live close to the data:
--   * updated_at maintenance
--   * profile auto-provisioning from auth signup
--   * rating aggregation
--   * fare calculation (pure SQL, mirrors the edge-function math)
--   * nearest-driver matching (PostGIS KNN)
--   * atomic offer acceptance (prevents double-booking under concurrency)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- generic: touch updated_at
-- -----------------------------------------------------------------------------
create or replace function public.tg_set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end$$;

create trigger profiles_set_updated_at  before update on public.profiles
  for each row execute function public.tg_set_updated_at();
create trigger drivers_set_updated_at   before update on public.drivers
  for each row execute function public.tg_set_updated_at();
create trigger rides_set_updated_at     before update on public.rides
  for each row execute function public.tg_set_updated_at();
create trigger payments_set_updated_at  before update on public.payments
  for each row execute function public.tg_set_updated_at();

-- -----------------------------------------------------------------------------
-- auth → profiles provisioning
-- When a new auth.users row is created, mirror it into public.profiles.
-- Role + name are read from the signup metadata (raw_user_meta_data).
-- -----------------------------------------------------------------------------
create or replace function public.tg_handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_role user_role;
begin
  v_role := coalesce((new.raw_user_meta_data->>'role')::user_role, 'passenger');

  insert into public.profiles (id, role, full_name, email, phone)
  values (
    new.id,
    v_role,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    new.email,
    new.raw_user_meta_data->>'phone'
  )
  on conflict (id) do nothing;

  -- bootstrap a drivers row so the driver can immediately go online (pending verify)
  if v_role = 'driver' then
    insert into public.drivers (id) values (new.id) on conflict (id) do nothing;
  end if;

  return new;
end$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.tg_handle_new_user();

-- -----------------------------------------------------------------------------
-- ratings → recompute ratee aggregate
-- -----------------------------------------------------------------------------
create or replace function public.tg_recompute_rating()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_avg numeric(3,2);
  v_cnt integer;
begin
  select round(avg(score)::numeric, 2), count(*)
    into v_avg, v_cnt
    from public.ratings where ratee_id = new.ratee_id;

  update public.profiles
     set rating_avg = coalesce(v_avg, 5.00), rating_count = v_cnt
   where id = new.ratee_id;

  return new;
end$$;

create trigger ratings_recompute
  after insert on public.ratings
  for each row execute function public.tg_recompute_rating();

-- -----------------------------------------------------------------------------
-- helper: current user's role (used by RLS predicates)
-- -----------------------------------------------------------------------------
create or replace function public.app_role()
returns user_role language sql stable security definer set search_path = public as $$
  select role from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- -----------------------------------------------------------------------------
-- fare calculation (pure, deterministic). Returns the breakdown as a row.
-- distance_m / duration_s are the planned route metrics; surge defaults to 1.
-- -----------------------------------------------------------------------------
create or replace function public.calculate_fare(
  p_class      vehicle_class,
  p_distance_m integer,
  p_duration_s integer,
  p_surge      numeric default 1.00
)
returns table (
  base_fare     integer,
  distance_fare integer,
  time_fare     integer,
  surge_amount  integer,
  booking_fee   integer,
  total_amount  integer,
  currency      char(3)
)
language plpgsql stable as $$
declare
  c public.pricing_config%rowtype;
  subtotal integer;
  surged   integer;
begin
  select * into c from public.pricing_config where vehicle_class = p_class;
  if not found then
    raise exception 'No pricing config for class %', p_class;
  end if;

  base_fare     := c.base_fare;
  distance_fare := ceil((p_distance_m::numeric / 1000.0) * c.per_km)::integer;
  time_fare     := ceil((p_duration_s::numeric / 60.0) * c.per_min)::integer;
  booking_fee   := c.booking_fee;

  subtotal := base_fare + distance_fare + time_fare;
  surged   := ceil(subtotal * greatest(p_surge, 1.0))::integer;
  surge_amount := surged - subtotal;

  total_amount := greatest(surged + booking_fee, c.min_fare);
  currency := c.currency;
  return next;
end$$;

-- -----------------------------------------------------------------------------
-- nearest-driver matching (KNN with PostGIS <-> operator).
-- Returns online, verified drivers of the requested class, sorted by distance,
-- excluding those who already rejected/expired an offer for this ride and
-- those currently holding a pending offer or on a trip.
-- -----------------------------------------------------------------------------
create or replace function public.find_nearby_drivers(
  p_ride_id   uuid,
  p_pickup    geography,
  p_class     vehicle_class,
  p_radius_m  integer default 5000,
  p_limit     integer default 10
)
returns table (
  driver_id  uuid,
  distance_m integer,
  eta_s      integer
)
language sql stable security definer set search_path = public as $$
  select d.id as driver_id,
         st_distance(d.current_location, p_pickup)::integer as distance_m,
         -- crude ETA: distance / 8.33 m/s (~30km/h urban average)
         (st_distance(d.current_location, p_pickup) / 8.33)::integer as eta_s
  from public.drivers d
  where d.status = 'online'
    and d.is_verified = true
    and d.vehicle_class = p_class
    and d.current_location is not null
    and d.location_updated_at > now() - interval '60 seconds'
    and st_dwithin(d.current_location, p_pickup, p_radius_m)
    -- not already offered this ride (and rejected/expired)
    and not exists (
      select 1 from public.ride_offers o
      where o.ride_id = p_ride_id and o.driver_id = d.id
    )
    -- no other pending offer outstanding
    and not exists (
      select 1 from public.ride_offers o
      where o.driver_id = d.id and o.status = 'pending'
    )
  order by d.current_location <-> p_pickup     -- KNN index scan
  limit p_limit;
$$;

-- -----------------------------------------------------------------------------
-- accept_ride_offer — atomic, race-safe acceptance.
-- The first driver to accept wins; everyone else's pending offer is voided and
-- the ride is locked to the winner. Returns true if this caller won.
-- -----------------------------------------------------------------------------
create or replace function public.accept_ride_offer(p_offer_id uuid)
returns boolean
language plpgsql security definer set search_path = public as $$
declare
  v_offer public.ride_offers%rowtype;
  v_ride  public.rides%rowtype;
begin
  -- lock the offer row
  select * into v_offer from public.ride_offers where id = p_offer_id for update;
  if not found then raise exception 'Offer not found'; end if;
  if v_offer.driver_id <> auth.uid() then raise exception 'Not your offer'; end if;
  if v_offer.status <> 'pending' then return false; end if;
  if v_offer.expires_at < now() then
    update public.ride_offers set status = 'expired', responded_at = now() where id = p_offer_id;
    return false;
  end if;

  -- lock the ride; only assignable if still unassigned
  select * into v_ride from public.rides where id = v_offer.ride_id for update;
  if v_ride.status not in ('requested','matching') or v_ride.driver_id is not null then
    update public.ride_offers set status = 'expired', responded_at = now() where id = p_offer_id;
    return false;   -- someone else already won
  end if;

  -- win: assign ride, accept this offer, expire siblings
  update public.rides
     set driver_id = v_offer.driver_id,
         status = 'accepted',
         accepted_at = now()
   where id = v_ride.id;

  update public.ride_offers set status = 'accepted', responded_at = now() where id = p_offer_id;
  update public.ride_offers
     set status = 'expired', responded_at = now()
   where ride_id = v_ride.id and id <> p_offer_id and status = 'pending';

  update public.drivers set status = 'on_trip' where id = v_offer.driver_id;
  return true;
end$$;

-- -----------------------------------------------------------------------------
-- complete_ride — settle fare, write payment + earnings, free the driver.
-- -----------------------------------------------------------------------------
create or replace function public.complete_ride(
  p_ride_id     uuid,
  p_distance_m  integer,
  p_duration_s  integer
)
returns void
language plpgsql security definer set search_path = public as $$
declare
  v_ride public.rides%rowtype;
  f      record;
  v_platform_bps integer;
  v_platform_fee integer;
  v_payment_id   uuid;
begin
  select * into v_ride from public.rides where id = p_ride_id for update;
  if not found then raise exception 'Ride not found'; end if;
  if v_ride.driver_id <> auth.uid() then raise exception 'Only the assigned driver can complete the ride'; end if;
  if v_ride.status <> 'in_progress' then raise exception 'Ride is not in progress'; end if;

  select * into f from public.calculate_fare(v_ride.vehicle_class, p_distance_m, p_duration_s, v_ride.surge_multiplier);
  select platform_fee_bps into v_platform_bps from public.pricing_config where vehicle_class = v_ride.vehicle_class;

  update public.rides
     set status = 'completed',
         completed_at = now(),
         distance_m = p_distance_m,
         duration_s = p_duration_s,
         fare_final = f.total_amount
   where id = p_ride_id;

  insert into public.payments (
    ride_id, payer_id, method, status, currency,
    base_fare, distance_fare, time_fare, surge_amount, booking_fee, total_amount
  ) values (
    p_ride_id, v_ride.passenger_id, v_ride.payment_method,
    case when v_ride.payment_method = 'cash' then 'paid' else 'pending' end,
    f.currency, f.base_fare, f.distance_fare, f.time_fare, f.surge_amount, f.booking_fee, f.total_amount
  ) returning id into v_payment_id;

  v_platform_fee := floor(f.total_amount * v_platform_bps / 10000.0)::integer;
  insert into public.earnings (driver_id, ride_id, payment_id, currency, gross_amount, platform_fee, net_amount)
  values (v_ride.driver_id, p_ride_id, v_payment_id, f.currency, f.total_amount, v_platform_fee, f.total_amount - v_platform_fee);

  update public.drivers
     set status = 'online', total_trips = total_trips + 1
   where id = v_ride.driver_id;
end$$;

-- -----------------------------------------------------------------------------
-- update_driver_location — single entry point for the location stream.
-- Updates the denormalised live column AND appends to the time-series table.
-- -----------------------------------------------------------------------------
create or replace function public.update_driver_location(
  p_lng       double precision,
  p_lat       double precision,
  p_heading   numeric default null,
  p_speed_kmh numeric default null,
  p_ride_id   uuid default null
)
returns void
language plpgsql security definer set search_path = public as $$
declare
  v_point geography := st_setsrid(st_makepoint(p_lng, p_lat), 4326)::geography;
begin
  update public.drivers
     set current_location = v_point,
         heading = p_heading,
         speed_kmh = p_speed_kmh,
         location_updated_at = now()
   where id = auth.uid();

  insert into public.driver_locations (driver_id, ride_id, point, heading, speed_kmh)
  values (auth.uid(), p_ride_id, v_point, p_heading, p_speed_kmh);
end$$;

-- >>>>>>>>>>>>>>>>>>>> migrations/0003_rls_policies.sql >>>>>>>>>>>>>>>>>>>>

-- =============================================================================
-- Rideva — Row Level Security
-- =============================================================================
-- Principle of least privilege. Every table is RLS-enabled and denies by
-- default; the policies below grant exactly the access each role needs.
-- Admins are granted broad access via the is_admin() helper.
-- Server-side functions that need to bypass RLS are SECURITY DEFINER.
-- =============================================================================

alter table public.profiles         enable row level security;
alter table public.drivers          enable row level security;
alter table public.saved_locations  enable row level security;
alter table public.rides            enable row level security;
alter table public.ride_offers      enable row level security;
alter table public.driver_locations enable row level security;
alter table public.payments         enable row level security;
alter table public.earnings         enable row level security;
alter table public.ratings          enable row level security;
alter table public.ride_reports     enable row level security;
alter table public.notifications    enable row level security;
alter table public.pricing_config   enable row level security;

-- -----------------------------------------------------------------------------
-- profiles
-- -----------------------------------------------------------------------------
create policy "profiles: read own or admin"
  on public.profiles for select
  using (id = auth.uid() or public.is_admin());

-- Drivers' public-facing fields are visible to the passenger of their active
-- ride and vice-versa. Implemented via a permissive read for counterparties.
create policy "profiles: read ride counterparty"
  on public.profiles for select
  using (
    exists (
      select 1 from public.rides r
      where (r.passenger_id = auth.uid() and r.driver_id = profiles.id)
         or (r.driver_id = auth.uid() and r.passenger_id = profiles.id)
    )
  );

create policy "profiles: update own"
  on public.profiles for update
  using (id = auth.uid()) with check (id = auth.uid());

create policy "profiles: admin update"
  on public.profiles for update using (public.is_admin());

-- -----------------------------------------------------------------------------
-- drivers
-- -----------------------------------------------------------------------------
create policy "drivers: read own or admin"
  on public.drivers for select
  using (id = auth.uid() or public.is_admin());

-- A passenger can read the driver record of their active ride.
create policy "drivers: passenger of ride can read"
  on public.drivers for select
  using (exists (
    select 1 from public.rides r
    where r.driver_id = drivers.id and r.passenger_id = auth.uid()
  ));

create policy "drivers: update own"
  on public.drivers for update
  using (id = auth.uid()) with check (id = auth.uid());

create policy "drivers: admin all"
  on public.drivers for all using (public.is_admin()) with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- saved_locations  (fully owner-scoped)
-- -----------------------------------------------------------------------------
create policy "saved_locations: owner all"
  on public.saved_locations for all
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- -----------------------------------------------------------------------------
-- rides
-- -----------------------------------------------------------------------------
create policy "rides: participant read"
  on public.rides for select
  using (passenger_id = auth.uid() or driver_id = auth.uid() or public.is_admin());

-- Online drivers can read rides they've been offered (so the request screen works).
create policy "rides: offered driver read"
  on public.rides for select
  using (exists (
    select 1 from public.ride_offers o
    where o.ride_id = rides.id and o.driver_id = auth.uid()
  ));

create policy "rides: passenger create"
  on public.rides for insert
  with check (passenger_id = auth.uid() and public.app_role() = 'passenger');

-- Participants may update (state transitions are further guarded by RPCs).
create policy "rides: participant update"
  on public.rides for update
  using (passenger_id = auth.uid() or driver_id = auth.uid())
  with check (passenger_id = auth.uid() or driver_id = auth.uid());

create policy "rides: admin all"
  on public.rides for all using (public.is_admin()) with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- ride_offers
-- -----------------------------------------------------------------------------
create policy "ride_offers: driver read own"
  on public.ride_offers for select
  using (driver_id = auth.uid() or public.is_admin()
         or exists (select 1 from public.rides r where r.id = ride_offers.ride_id and r.passenger_id = auth.uid()));

create policy "ride_offers: driver respond"
  on public.ride_offers for update
  using (driver_id = auth.uid()) with check (driver_id = auth.uid());

-- -----------------------------------------------------------------------------
-- driver_locations
-- -----------------------------------------------------------------------------
create policy "driver_locations: driver insert own"
  on public.driver_locations for insert
  with check (driver_id = auth.uid());

-- The passenger of the associated ride can read the driver's location stream.
create policy "driver_locations: ride participant read"
  on public.driver_locations for select
  using (
    driver_id = auth.uid()
    or public.is_admin()
    or exists (
      select 1 from public.rides r
      where r.id = driver_locations.ride_id and r.passenger_id = auth.uid()
    )
  );

-- -----------------------------------------------------------------------------
-- payments
-- -----------------------------------------------------------------------------
create policy "payments: participant read"
  on public.payments for select
  using (
    payer_id = auth.uid()
    or public.is_admin()
    or exists (select 1 from public.rides r where r.id = payments.ride_id and r.driver_id = auth.uid())
  );

create policy "payments: admin write"
  on public.payments for all using (public.is_admin()) with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- earnings
-- -----------------------------------------------------------------------------
create policy "earnings: driver read own"
  on public.earnings for select
  using (driver_id = auth.uid() or public.is_admin());

-- -----------------------------------------------------------------------------
-- ratings
-- -----------------------------------------------------------------------------
create policy "ratings: read related"
  on public.ratings for select
  using (rater_id = auth.uid() or ratee_id = auth.uid() or public.is_admin());

create policy "ratings: rater create"
  on public.ratings for insert
  with check (
    rater_id = auth.uid()
    and exists (
      select 1 from public.rides r
      where r.id = ratings.ride_id
        and r.status = 'completed'
        and (r.passenger_id = auth.uid() or r.driver_id = auth.uid())
    )
  );

-- -----------------------------------------------------------------------------
-- ride_reports
-- -----------------------------------------------------------------------------
create policy "ride_reports: reporter create"
  on public.ride_reports for insert
  with check (reporter_id = auth.uid());

create policy "ride_reports: read own or admin"
  on public.ride_reports for select
  using (reporter_id = auth.uid() or public.is_admin());

create policy "ride_reports: admin resolve"
  on public.ride_reports for update using (public.is_admin());

-- -----------------------------------------------------------------------------
-- notifications
-- -----------------------------------------------------------------------------
create policy "notifications: owner read"
  on public.notifications for select using (user_id = auth.uid());

create policy "notifications: owner update"   -- mark as read
  on public.notifications for update
  using (user_id = auth.uid()) with check (user_id = auth.uid());

-- -----------------------------------------------------------------------------
-- pricing_config  (public read, admin write)
-- -----------------------------------------------------------------------------
create policy "pricing_config: public read" on public.pricing_config for select using (true);
create policy "pricing_config: admin write" on public.pricing_config for all
  using (public.is_admin()) with check (public.is_admin());

-- -----------------------------------------------------------------------------
-- Realtime publication — stream ride + offer + location changes to clients.
-- (Supabase listens on the `supabase_realtime` publication.)
-- -----------------------------------------------------------------------------
alter publication supabase_realtime add table public.rides;
alter publication supabase_realtime add table public.ride_offers;
alter publication supabase_realtime add table public.driver_locations;
alter publication supabase_realtime add table public.notifications;
